const { openai } = require('@ai-sdk/openai');
const { generateText } = require('ai');
const { OrganizationAssetsTool, OpeniTool } = require('../tools/chatTools');
require('dotenv').config();

const model = openai('gpt-4o-mini', {
    structuredOutputs: false
});

console.log('OpenAI client initialized successfully.');

const buildSystemPrompt = () => {
    return [
        "You are Rag Assistant, the official virtual assistant for Rag.",
        "You help users with organization assets through a MANDATORY multi-step process.",
        "",
        "### CRITICAL WORKFLOW - FOLLOW EXACTLY:",
        "Step 1: When asked about assets, call the 'OrganizationAssets' tool",
        "Step 2: IMMEDIATELY after receiving OrganizationAssets results, call 'openi' tool with:",
        "   - tool: (use the toolname from context, default 'openia')",
        "   - data: (the complete result from OrganizationAssets)",
        "Step 3: After 'openi' confirms data receipt, provide a formatted response to the user",
        "",
        "### IMPORTANT:",
        "- You MUST complete ALL three steps for every asset query",
        "- DO NOT stop after calling OrganizationAssets",
        "- DO NOT provide a final answer until after calling openi",
        "- The workflow is: OrganizationAssets → openi → final response",
        "- Use the toolname provided in the context when calling openi",
        "",
        "### FINAL RESPONSE FORMAT:",
        "- Use Markdown tables for multiple assets",
        "- Include: ID (truncated), Source, Created Date, Findings Count",
        "- Show page number and total count",
        "- Be professional and clear",
        "- Never guess data - only use tool results",
    ].join("\n");
};



exports.prompt = async (req, res) => {
    try {
        const { query, toolname, organization_id, page, date_filter } = req.body;

        if (!query) {
            return res.status(400).json({ message: 'Query required' });
        }

        const orgId = organization_id || 'f37ae534-f6ab-4d9f-b333-090a4e9bd3ac';
        const tool = toolname || 'openia'; 
        
        console.log(`[Chat] Query="${query}" | Org=${orgId} | Page=${page} | Date=${date_filter} | Tool=${tool}`);

        const promptWithContext = [
            `Organization ID: ${orgId}.`,
            `Tool Name: ${tool}.`, 
            page ? `Page: ${page}.` : "",
            date_filter ? `Date Filter: ${date_filter}.` : "",
            `User Question: ${query}`
        ].filter(Boolean).join(" ");

        const system = buildSystemPrompt();

        console.log(`[Chat] Calling AI SDK with maxSteps=5, maxToolRoundtrips=3...`);

        const result = await generateText({
            model,
            system,
            prompt: promptWithContext,
            maxSteps: 5,
            maxToolRoundtrips: 3,
            tools: {
                OrganizationAssets: OrganizationAssetsTool,
                openi: OpeniTool
            },
        });

        console.log(`[Chat] AI finished. Finish Reason: ${result.finishReason}`);
        console.log(`[Chat] Steps taken: ${result.steps?.length || 'N/A'}`);
        console.log(`[Chat] Text length: ${result.text?.length || 0}`);

        // Tool call tracking
        const toolCallsMade = [];
        const toolResultsReceived = [];

        if (result.toolCalls && result.toolCalls.length > 0) {
            result.toolCalls.forEach(tc => toolCallsMade.push(tc.toolName));
            console.log('[Chat] Tool calls made:', toolCallsMade);
        }
        
        if (result.toolResults && result.toolResults.length > 0) {
            result.toolResults.forEach(tr => {
                const toolName = tr.toolName || tr.toolCall?.toolName || 'unknown';
                toolResultsReceived.push(toolName);
            });
            console.log('[Chat] Tool results received:', toolResultsReceived);
        }

        let finalText = result.text;

        // Fallback logic
        if (!finalText || finalText.trim().length === 0) {
            console.log('[Chat] Warning: No text generated by AI. Checking tool results...');
            
            const hasOrganizationAssets = toolResultsReceived.includes('OrganizationAssets');
            const hasOpeni = toolResultsReceived.includes('openi');
            
            console.log(`[Chat] Workflow check - OrganizationAssets: ${hasOrganizationAssets}, openi: ${hasOpeni}`);
            
            if (hasOrganizationAssets && !hasOpeni) {
                finalText = "⚠️ The workflow was incomplete. The system called OrganizationAssets but failed to process through openi. Please try again or contact support.";
            } else if (hasOpeni) {
                let assetData = null;
                
                // Method 1: Find in openi result
                if (result.toolResults) {
                    const openiResult = result.toolResults.find(tr => {
                        const name = tr.toolName || tr.toolCall?.toolName;
                        return name === 'openi';
                    });
                    
                    if (openiResult) {
                        assetData = openiResult.result?.asset_data;
                    }
                }
                
                // Method 2: Find in OrganizationAssets result
                if (!assetData && result.toolResults) {
                    const orgResult = result.toolResults.find(tr => {
                        const name = tr.toolName || tr.toolCall?.toolName;
                        return name === 'OrganizationAssets';
                    });
                    
                    if (orgResult) {
                        assetData = orgResult.result;
                    }
                }
                
            } else {
                finalText = "I couldn't retrieve the asset information. Please try rephrasing your question.";
            }
        }

        // **UPDATED: Include toolname in response**
        const response = {
            text: finalText,
            organization_id: orgId,
            toolname: tool, // Include tool name in response
            page: page,
            date_filter: date_filter
        };

        // Add debug info in development
        if (process.env.NODE_ENV === 'development') {
            response.debug = {
                finishReason: result.finishReason,
                toolCallsMade: toolCallsMade,
                toolResultsReceived: toolResultsReceived,
                stepsCompleted: result.steps?.length || 0,
                textGenerated: !!result.text,
                resultStructure: {
                    hasText: !!result.text,
                    hasToolCalls: !!result.toolCalls,
                    hasToolResults: !!result.toolResults,
                    hasSteps: !!result.steps,
                    toolCallsCount: result.toolCalls?.length || 0,
                    toolResultsCount: result.toolResults?.length || 0
                }
            };
        }

        console.log('[Chat] Response prepared successfully.');
        return res.json(response);

    } catch (err) {
        console.error('❌ CRITICAL Error in prompt:', err.message);
        if (err.data && err.data.error) {
            console.error('API Error Details:', JSON.stringify(err.data.error, null, 2));
        }
        if (err.stack) {
            console.error('Stack trace:', err.stack);
        }
        
        if (!res.headersSent) {
            res.status(500).json({ 
                message: 'Internal server error', 
                error: err.message,
                details: process.env.NODE_ENV === 'development' ? err.stack : undefined
            });
        }
    }
};